name: todo_sample1
description: Sample TODO app with polymer2+DDC
version: 0.0.1
dependencies:
 logging: any
 polymer_element: any
#   path: ../../polymer_element

dependency_overrides:
 polymer_element:
  path: ../../polymer_element
